version: '3.3'

services:
  fastapi-lbp:
    image: python:3.9-slim-bullseye
    container_name: fastapi_lbp
    working_dir: /app
    volumes:
      - ./LBP:/app
    ports:
      - "8000:8000"
    command: /app/start.sh
    networks:
      - mynetwork

  fastapi-minivgg:
    image: python:3.9-slim-bullseye
    container_name: fastapi_minivgg
    working_dir: /app
    volumes:
      - ./miniVGG:/app
    ports:
      - "8001:8001"
    command: /app/start.sh
    networks:
      - mynetwork

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
      
